version: '3'

services:
  app:
    image: webinventions.pl:5000/kardaszeu
    build: ./
    ports:
      - "${BIND_ADDRESS:-127.0.0.1}:${BIND_PORT:-8080}:80"
    volumes:
      - ./:/var/www
    working_dir: /var/www
    env_file:
      - .env
    environment:
      TZ: Europe/Warsaw
